server:
  port: 8081

spring:
  application:
    name: blog-service
  datasource:
    url: jdbc:postgresql://auth-blog.cvmo4iemgf4b.eu-central-1.rds.amazonaws.com/auth_blog
    username: postgres
    password: postgres-pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    url: /blog/v3/api-docs
    path: /open/api/swagger-ui.html
    config-url: /blog/v3/api-docs/swagger-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://3.79.186.154:8761/eureka/
  instance:
    preferIpAddress: true