server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_auth
    username: dbuser
    password: password0506
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect